# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Day_of_weeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_def', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_def', models.CharField(max_length=255)),
                ('fclt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Faculties')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SCHEDULES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parity', models.DecimalField(decimal_places=0, max_digits=1)),
                ('time_of', models.TimeField()),
                ('place', models.CharField(max_length=50)),
                ('start_week', models.CharField(max_length=255)),
                ('end_week', models.CharField(max_length=255)),
                ('priority_YN', models.CharField(max_length=1)),
                ('comment', models.CharField(max_length=255)),
                ('cthd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Cathedras')),
                ('dfwk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Day_of_weeks')),
                ('grp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_year', models.CharField(max_length=4)),
                ('cthd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Cathedras')),
                ('fclt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Faculties')),
                ('grp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(max_length=255)),
                ('name_full', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='unvr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Universities'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='subj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Subjects'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='tchr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Teachers'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Students'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faculties',
            name='unvr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Universities'),
        ),
        migrations.AddField(
            model_name='cathedras',
            name='fclt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intodayer2_app.Faculties'),
        ),
    ]
