# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intodayer2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
