# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intodayer2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMailingChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_yn', models.CharField(blank=True, max_length=1)),
                ('telegram_yn', models.CharField(blank=True, max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
