# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intodayer2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivToPng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=1000, upload_to='div_to_png/')),
            ],
            options={
                'db_table': 'div_to_png',
                'managed': True,
            },
        ),
    ]
