# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import extra.validators


class Migration(migrations.Migration):

    dependencies = [
        ('intodayer2_app', '0002_usermailingchannels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermailingchannels',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='chat_id',
            field=models.CharField(blank=True, max_length=15, validators=[extra.validators.validate_telegram_chat_id_field]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, validators=[extra.validators.validate_email_field]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[extra.validators.validate_not_empty_filed]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[extra.validators.validate_not_empty_filed]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[extra.validators.validate_phone_field]),
        ),
        migrations.AlterField(
            model_name='daysofweek',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[extra.validators.validate_day_of_week_field]),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='confirmed_yn',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[extra.validators.validate_yn_filed]),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='email',
            field=models.TextField(validators=[extra.validators.validate_email_field]),
        ),
        migrations.AlterField(
            model_name='planlists',
            name='start_date',
            field=models.DateTimeField(blank=True, validators=[extra.validators.validate_date_field]),
        ),
        migrations.AlterField(
            model_name='planlists',
            name='title',
            field=models.CharField(max_length=256, validators=[extra.validators.validate_not_empty_filed]),
        ),
        migrations.AlterField(
            model_name='planrows',
            name='comment',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='planrows',
            name='end_week',
            field=models.IntegerField(validators=[extra.validators.validate_weeks_duration_field]),
        ),
        migrations.AlterField(
            model_name='planrows',
            name='parity',
            field=models.IntegerField(blank=True, null=True, validators=[extra.validators.validate_parity_field], verbose_name=django.db.models.deletion.DO_NOTHING),
        ),
        migrations.AlterField(
            model_name='planrows',
            name='start_week',
            field=models.IntegerField(validators=[extra.validators.validate_weeks_duration_field]),
        ),
        migrations.AlterField(
            model_name='planrowstemporal',
            name='end_week',
            field=models.IntegerField(validators=[extra.validators.validate_weeks_duration_field]),
        ),
        migrations.AlterField(
            model_name='planrowstemporal',
            name='parity',
            field=models.BooleanField(validators=[extra.validators.validate_parity_field]),
        ),
        migrations.AlterField(
            model_name='planrowstemporal',
            name='start_week',
            field=models.IntegerField(validators=[extra.validators.validate_weeks_duration_field]),
        ),
        migrations.AlterField(
            model_name='times',
            name='hh24mm',
            field=models.TimeField(validators=[extra.validators.validate_time_field]),
        ),
        migrations.AlterField(
            model_name='usermailingchannels',
            name='email_yn',
            field=models.CharField(max_length=1, validators=[extra.validators.validate_yn_filed]),
        ),
        migrations.AlterField(
            model_name='usermailingchannels',
            name='telegram_yn',
            field=models.CharField(max_length=1, validators=[extra.validators.validate_yn_filed]),
        ),
        migrations.AlterField(
            model_name='userplans',
            name='current_yn',
            field=models.CharField(max_length=1, validators=[extra.validators.validate_yn_filed]),
        ),
        migrations.AlterField(
            model_name='userplans',
            name='role',
            field=models.CharField(max_length=12, validators=[extra.validators.validate_role_field]),
        ),
    ]
