# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intodayer2_app', '0002_auto_20161212_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeeks',
            fields=[
                ('dfwk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('_def', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'day_of_weeks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchedulesSpecial',
            fields=[
                ('schld_s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of', models.DateField(blank=True, null=True)),
                ('parity', models.NullBooleanField()),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('start_week', models.IntegerField(blank=True, null=True)),
                ('end_week', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'schedules_special',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('tms_id', models.IntegerField(primary_key=True, serialize=False)),
                ('_def', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'times',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Day_of_weeks',
        ),
        migrations.AlterModelOptions(
            name='cathedras',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='faculties',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='schedules',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='universities',
            options={'managed': False},
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='student_id',
            new_name='stdt_stdt_id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='delivery_yn',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='navi_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='navi_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
